site:
  title: ThoughtSpot Seekwell Documentation
  url: https://seekwell-docs.netlify.app/seekwell/0.0/
  start_page: ROOT:index.adoc
content:
  sources:
  # embedding empty credentials in the URL disables the Edit this Page link for any page created from this repository  - url: ./
  - url: git@github.com:thoughtspot/seekwell-docs.git
    branches: ['main']
    start_path: seekwell/
ui:
  bundle:
    url: ui-bundle/ui2-bundle.zip
  supplemental_files:
  - path: .nojekyll
  - path: ui.yml
    contents: "static_files: [ .nojekyll ]"
    snapshot: true
asciidoc:
  attributes:
    tabs: tabs
  extensions:
    - "@djencks/asciidoctor-tabset-block"

output:
  clean: true
  dir: build/seekwell
