[build.environment]
CI = "true"
NODE_VERSION = "10"
NPM_CONFIG_OPTIONAL = "false"
ANTORA_CACHE_DIR = "node_modules/.cache/antora"

[build]
command = "node_modules/.bin/antora antora-playbook.yml --stacktrace"

[[redirects]]
  from = "/*"
  to = "https://seekwell-docs.netlify.app/seekwell/0.0/"
  status = 200
  force = true # COMMENT: ensure that we always redirect
