= Connect to a local database
:last_updated: 07/27/2021
:experimental:
:linkattrs:

You can get SeekWell to work with a local database using *ngrok*.

Use the following information:

* https://medium.com/@jotarios/ngrok-secure-tunnels-local-dead8685bd71[https://ngrok.com/docs^]
* https://ngrok.com/docs[https://ngrok.com/docs^]

== Exposing networked services

TCP tunnels enable you to expose any networked service that runs over TCP. You can use it to expose SSH, game servers like Minecraft, databases and much more.

Starting a TCP tunnel is easy; you must rist sign up, for free, to expose the type of service.

. https://dashboard.ngrok.com/signup[Sign up for ngrok^].

. https://dashboard.ngrok.com/get-started[Get your authtoken^].

. Install your authtoken, by running the following at the command propt:
+
[source]
----
$ ngrok authtoken YOUR_TOKEN_HERE
----
. Create your secure tunnel, by running this at the command prompt:
+
[source]
----
$ ngrok tcp port
----
+
For example, to expose a MySQL database with port `3306`, run this command:
+
[source]
----
$ ngrok tcp 3306
----

. After the service starts, it reports its status:
+
[source]
----
Session Status        online

 Account               jotarios (Plan: Free)
 Version               2.2.8
 Region                United States (us)
 Web Interface         http://127.0.0.1:4041
 Forwarding            tcp://0.tcp.ngrok.io:14563 -> localhost:3306
 Connections           ttl opn rt1 rt5 p50 p90 68 0 0.00 0.00 0.89 28.70
----

In this example, you can access to your database through the URL `0.tcp.ngrok.io:14563`

Easy, right?
